# cocktails = ["Vesper", "Bacardi", "Negroni", "Rose", "Old Fashioned", "Tuxedo", "Mojito", "Horse's Neck", "Planter's Punch", "Sea Breeze", "Pisco Sour", "Long Island Iced Tea", "Clover Club", "Angel Face", "Mimosa", "Whiskey Sour", "Screwdriver", "Cuba Libre", "Manhattan", "Porto Flip", "Gin Fizz", "Espresso Martini", "Margarita", "French 75", "Yellow Bird", "Pina Colada", "Aviation", "Bellini", "Grasshopper", "Tequila Sunrise", "Daiquiri", "Rusty Nail", "B52", "Stinger", "Golden Dream", "God Mother", "Spritz Veneziano", "Bramble", "Alexander", "Lemon Drop Martini", "French Martini", "Black Russian", "Bloody Mary", "Mai-tai", "Barracuda", "Sex on the Beach", "Monkey Gland", "Derby", "Sidecar", "Irish Coffee", "Sazerac", "Americano", "Singapore Sling", "French Connection", "Moscow Mule", "John Collins", "Kir", "Mint Julep", "Tommy's Margarita", "Paradise", "Dirty Martini", "Champagne Cocktail", "Mary Pickford", "Hemingway Special", "Dark 'n' Stormy", "Ramos Fizz", "Russian Spring Punch", "God Father", "Cosmopolitan", "Dry Martini", "Between the Sheets", "Casino", "Caipirinha", "Vampiro", "Kamikaze", "White Lady", "Harvey Wallbanger"]

# ingredients = ["Light rum", "Applejack", "Gin", "Dark rum", "Sweet Vermouth", "Strawberry schnapps", "Scotch", "Apricot brandy", "Triple sec", "Southern Comfort", "Orange bitters", "Brandy", "Lemon vodka", "Blended whiskey", "Dry Vermouth", "Amaretto", "Tea", "Champagne", "Coffee liqueur", "Bourbon", "Tequila", "Vodka", "Anejo rum", "Bitters", "Sugar", "Kahlua", "demerara Sugar", "Dubonnet Rouge", "Lime juice", "Irish whiskey", "Apple brandy", "Carbonated water", "Cherry brandy", "Creme de Cacao", "Grenadine", "Port", "Coffee brandy", "Red wine", "Rum", "Grapefruit juice", "Ricard", "Sherry", "Cognac", "Sloe gin", "Apple juice", "Pineapple juice", "Lemon juice", "Sugar syrup", "Milk", "Strawberries", "Chocolate syrup", "Yoghurt", "Mango", "Ginger", "Lime", "Cantaloupe", "Berries", "Grapes", "Kiwi", "Tomato juice", "Cocoa powder", "Chocolate", "Heavy cream", "Galliano", "Peach Vodka", "Ouzo", "Coffee", "Spiced rum", "Water", "Espresso", "Angelica root", "Orange", "Cranberries", "Johnnie Walker", "Apple cider", "Everclear", "Cranberry juice", "Egg yolk", "Egg", "Grape juice", "Peach nectar", "Lemon", "Firewater", "Lemonade", "Lager", "Whiskey", "Absolut Citron", "Pisco", "Irish cream", "Ale", "Chocolate liqueur", "Midori melon liqueur", "Sambuca", "Cider", "Sprite", "7-Up", "Blackberry brandy", "Peppermint schnapps", "Creme de Cassis", "Jack Daniels", "Bailey's irish cream", "151 proof rum", "Absolut Vodka", "Goldschlager", "Crown Royal", "Cointreau", "Vermouth", "Advocaat", "Absolut Kurant", "Beer", "Kool-Aid", "Cherry Heering", "White Creme de Menthe", "Malibu rum", "Vanilla vodka", "Jagermeister", "Kiwi liqueur", "Grand Marnier", "Cachaca", "Peachtree schnapps", "Wild Turkey", "Cranberry vodka", "Corona", "Orange juice", "Yukon Jack", "Chocolate ice-cream", "Coconut rum", "Banana liqueur", "Black Sambuca", "Hot Damn", "Mint", "Campari", "Ice", "Sour mix", "Absinthe", "Whisky", "Guinness stout", "Vanilla ice-cream", "Chambord raspberry liqueur", "Jim Beam", "Godiva liqueur", "Fruit punch", "Baileys irish cream", "Zima", "Blue Curacao", "Coca-Cola", "Maui", "Frangelico", "Bacardi Limon", "Raspberry vodka", "Green Creme de Menthe", "Lemon peel", "Prosecco", "White Rum", "Mezcal", "Green Chartreuse", "Grape Soda", "Hot Chocolate", "Blended Scotch", "Rye whiskey"]

ingredients = ["apple", "pear", "orange", "lemon", "banana", "watermelon", "grapes", "strawberry", "cherry", "pineapple", "coconut", "kiwi", "tomato", "avocado"]

# cocktails.each do |cocktail|
#   Cocktail.create!(name: cocktail)
# end

ingredients.each do |ingredient|
  Ingredient.create!(name: ingredient)
end
